### PR TITLE
Added template page

### PR DESCRIPTION
**Pull request by kxtmg**
Created basic template page based on figma design.

### CODE REVIEW

**Comment by davidxiong117** [comment]
add /images before src="/ui-shop-tool-kit.png"

so like src="/images/ui-shop-tool-kit.png"

image wasn't loading correctly.

also link the docs button to actual docs page--it should exist soon if someone checks out my pr

**Review by davidxiong117 — CHANGES_REQUESTED** [review]
add /images before src="/ui-shop-tool-kit.png"

so like src="/images/ui-shop-tool-kit.png"

image wasn't loading correctly.

also link the docs button to actual docs page--it should exist soon if someone checks out my pr

**Comment by kxtmg** [comment]
I've made the changes as requested. Please review them when you get a chance

**Review by missile720 — APPROVED** [review]
Looks good!

**Review by sorayaboza — APPROVED** [review]
Looks good!

**Review by AlissonRoss — APPROVED** [review]
Awesome work

**Review by davidxiong117 — APPROVED** [review]

**Pull request merged**
