### PR TITLE
3 components page

### LINKED ISSUE #3: components page

### PR DESCRIPTION
**Pull request by missile720**
## Images
Capture

## Changes
1. Created initial components page layout

## Purpose
User can now navigate to different types of components

## Approach
Using components to render different parts of the page without having to leave the component page

## Learning
N/A

_If this closes an issue, reference the issue here. If it doesn't, remove this line_
Closes #3

### CODE REVIEW

**Review by eLadd416 — APPROVED** [review]
Looks wonderfull

**Review by sorayaboza — APPROVED** [review]
Looks great!

**Review by NathanDuncan-coder — APPROVED** [review]
Looks good.

**Review by AlissonRoss — COMMENTED** [review]
Good start.

**Pull request merged**
